### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by XksA-me** [HighwayWu/DeepFakeDefenders#1]
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/b0997ac3-5fb3-4366-ad21-fbfe89974795">

If you encounter the "cv2 circular import" problem again, you can upgrade opencv-python and run the following command:
```bash
pip install -U opencv-python 
```

I use version 4.10.0.84 and it works fine.

**Comment by HighwayWu** [comment]
Thank you for your comments, it will definitely help developers better.
