### ISSUE TITLE
Low confidence when detecting obviously deepfakes

### ISSUE THREAD

**Issue by Daleyzw** [HighwayWu/DeepFakeDefenders#10]
<img width="350" alt="ai2" src="https://github.com/user-attachments/assets/67a50c01-d970-4456-ba51-b24e76e87f29">
这个结果是： 0.2054801881313324

<img width="350" alt="ai2" src="https://github.com/user-attachments/assets/182a1708-af94-4a1b-a778-227e9deb4dfe">
这个结果是：0.083944887

**Comment by HighwayWu** [comment]
Thank you for your question. I think there are two reasons:
- The model of this project is trained on pre-processed data (pre-cropped and aligned faces), so it may not be suitable for portraits with large distribution differences. It is recommended to crop the image to 512*512 with the face centered.
- Generalization (i.e. detecting cross-domain forgeries) has always been the core indicator of the Deepfake Detection task. Unfortunately, there is currently no well-defined solution to deal with the ever-changing forgeries. This is also the goal of this competition and this project, to build a powerful general deepfake detector.
