### ISSUE TITLE
some questions about the finally input

### ISSUE THREAD

**Issue by H-jianfei** [HighwayWu/DeepFakeDefenders#13]
First of all, thank you for your open source project, which is very helpful to us, but I would like to ask you about the finally input.
![image](https://github.com/user-attachments/assets/2a0726dd-6802-42bd-a23a-dd0a2f332d0e)
I entered these two addresses in the development machine, but an "error" is popped up in both cases.
![image](https://github.com/user-attachments/assets/01da7e6a-05f4-4a45-82df-17f97df78fa7)

**Comment by HighwayWu** [comment]
Thanks for your attention. Please delete the "try, except" module in the infer.py, and check the specific error information.

**Comment by H-jianfei** [comment]
Thanks I find the problem it’s about the gpu memory🫡
