### ISSUE TITLE
What are the computer requirements for fine-tuning on this model

### ISSUE THREAD

**Issue by Jayden-qing** [HighwayWu/DeepFakeDefenders#15]
Thank you very much for open sourcing this model.When I try to fine-tuning on this model,I get "CUDA out of memory" error.Could author suggest suitable GPU memory for this model

**Comment by HighwayWu** [comment]
Thanks for your asking. The amount of GPU memory required for training depends on the number of experts used in the model and the image batch size. It is recommended to use a single expert (such as EfficientNet-B4) and a batch size of 16 for training. In this case, a 24GB RTX-3090 should be suitable.
