### ISSUE TITLE
how to pre-process the input image?

### ISSUE THREAD

**Issue by zcbfpramtqs55675** [HighwayWu/DeepFakeDefenders#16]
hi, first thank you for open sourcing this model! but I have the question about how to pre-process the input image both training and  infer, hope for your reply.

**Comment by HighwayWu** [comment]
Thanks for your asking. The data for this competition is pre-processed by the organizer. We think the following process could be used for your own data: first use RetinaFace (or other face recognition models) for face recognition, then center align and crop the area 1.3 times the default size, and finally scale it to 512*512 size.

**Comment by zcbfpramtqs55675** [comment]
> Thanks for your asking. The data for this competition is pre-processed by the organizer. We think the following process could be used for your own data: first use RetinaFace (or other face recognition models) for face recognition, then center align and crop the area 1.3 times the default size, and finally scale it to 512*512 size.

thanks！
