### ISSUE TITLE
Inconsistent prediction results for test data

### ISSUE THREAD

**Issue by XksA-me** [HighwayWu/DeepFakeDefenders#2]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/3c469fb5-ad1c-4387-a01b-14808130576a">

I really appreciate that you have open-sourced this project and the corresponding pre-trained model. I have a question. I am currently using your model and code, and the prediction results of the test pictures are inconsistent with your annotations. What might be the reason for this?

**My environment:**
NVIDIA RTX A4000 16G video memory
Ubuntu 18.04
CUDA 11.1

The Python environment is consistent with your description.
```bash
torch==1.9.0
timm==1.0.8
scikit-learn==1.2.1
torch-ema==0.3
torch_kmeans==0.2.0
albumentations==1.3.1
opencv-python==4.10.0.84
```

**Comment by zhanpengjie** [comment]
me too
Please input the image path:
demo/img_1_should_be_0.0016829653177410.jpg
Prediction of [demo/img_1_should_be_0.0016829653177410.jpg] being Deepfake: 0.587238550
Please input the image path:
demo/img_2_should_be_0.9854894280433655.jpg
Prediction of [demo/img_2_should_be_0.9854894280433655.jpg] being Deepfake: 0.687471569

**Comment by HighwayWu** [comment]
Sorry for the wrong prediction, which can be corrected by the new weight of the [link](https://pan.baidu.com/s/1hh6Rub60T7UXok5rqACffQ?pwd=gxu5). This problem is due to a transmission error when uploading to Baidu Pan. Thank you for pointing out the problem!

**Comment by XksA-me** [comment]
> Sorry for the wrong prediction, which can be corrected by the new weight of the [link](https://pan.baidu.com/s/1hh6Rub60T7UXok5rqACffQ?pwd=gxu5). This problem is due to a transmission error when uploading to Baidu Pan. Thank you for pointing out the problem!

Cool, after replacing the new model, the test data test output results are normal.

Thank you for your reply.

**Comment by XksA-me** [comment]
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/dddfbc65-86e0-4df4-9287-944082dc57dd">
Want to contribute to the project, I have done a job and used GPT to assist in generating API and webUI call versions for the project. I expect to submit the PR tonight, hoping to make it more convenient for everyone to use.

**Comment by yqj0919** [comment]
我更换权重<img width="1127" alt="image" src="https://github.com/user-attachments/assets/ac4c6aef-8dad-49a5-b663-b40425e8d6fd">

**Comment by chloeadrian12** [comment]
> 我更换权重<img alt="image" width="1127" src="https://private-user-images.githubusercontent.com/85222546/365448577-ac4c6aef-8dad-49a5-b663-b40425e8d6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTQyMjQsIm5iZiI6MTcyNTg1MzkyNCwicGF0aCI6Ii84NTIyMjU0Ni8zNjU0NDg1NzctYWM0YzZhZWYtOGRhZC00OWE1LWI2NjMtYjQwNDI1ZThkNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZGZkMTQ4ZjliYzhiNTNhZWM3OWE3MzgwNjIxNThhMGNjYjQ3ZTk5ODI2YThhOTY3ODQ0YWNhMDY4MmFmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmS-ftFxz1ZC1fNX5QIxOK-vEIjEPsapa7F1h3EHCQA">

I got the right results after exchanging the weight. Maybe there are some problems with your environment.

**Comment by HighwayWu** [comment]
Please re-open this issue if you encounter a case where the predictions do not match. Thank you for your attention again.

**Comment by chloeadrian12** [comment]
这是来自QQ邮箱的自动回复邮件。您的邮件已经收到，请耐心等待回复，感谢理解。

**Comment by chloeadrian12** [comment]
这是来自QQ邮箱的自动回复邮件。您的邮件已经收到，请耐心等待回复，感谢理解。
