### ISSUE TITLE
无法获取期望数值

### ISSUE THREAD

**Issue by smthemex** [HighwayWu/DeepFakeDefenders#3]
![image](https://github.com/user-attachments/assets/891c0af1-c2cf-4dab-a839-b17cdf6d74ae)
预测值波动较大，与实际期望差距明显。

**Comment by HighwayWu** [comment]
Sorry for the wrong prediction, which can be corrected by the new weight of the [link](https://pan.baidu.com/s/1hh6Rub60T7UXok5rqACffQ?pwd=gxu5). This problem is due to a transmission error when uploading to Baidu Pan. Thank you for pointing out the problem!

**Comment by smthemex** [comment]
Your project is very meaningful。
