### ISSUE TITLE
想知道您会把分数多少当作真假的区别分数

### ISSUE THREAD

**Issue by chalengr** [HighwayWu/DeepFakeDefenders#4]
想知道您会把分数多少当作真假的区别分数

**Comment by HighwayWu** [comment]
Thank you for your question. Our project aims to predict the probability of belonging to deepfake, so we do not set a fixed threshold to binarize the output. Simply setting 0.5 as the threshold is a balanced choice, or raising the threshold to reduce false alarms according to your application environment.
