### ISSUE TITLE
pretrained weights in google drive

### ISSUE THREAD

**Issue by zisianw** [HighwayWu/DeepFakeDefenders#7]
hello, great work! was wondering if you have pretrained weights in google drive for folks who do not have baidu pan?

**Comment by HighwayWu** [comment]
Sure, we will share the weights in Google Drive. Thanks for your suggestion.

**Comment by HighwayWu** [comment]
The weight now can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1OQkkBn-Wv9PTHaxhXs_JF1IdkIES64pm?usp=sharing).
